name: push
on:
  push:
    branches: [ develop ]
jobs:
  report:
      name: Report webpack stats
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@master
      - name: Report webpack stats
        uses: packtracker/report@2.3.0
        env:
          PT_PROJECT_TOKEN: ${{ secrets.PT_PROJECT_TOKEN }}
          WEBPACK_CONFIG_PATH: ./webpack.config.prod.js
